### ISSUE TITLE
Update vignette to show changes to API

### ISSUE THREAD

**Issue by biobenkj** [biobenkj/compartmap#5]
Update vignette to use latest functions and note deprecated functions/wrappers (e.g. getCompartments).

**Comment by ttriche** [comment]
and/or just use velocessor ;-) 

see version bump for that.

Compartmap will benefit from checking that an SE/SCE has length(unique(genome(x))) > 0 before transforming. 

ask me how I know this

**Comment by biobenkj** [comment]
Done.
